export const pulls = [
  {
    "url": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/36",
    "id": 201657893,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MjAxNjU3ODkz",
    "html_url": "https://github.com/bridge-school/bridgeschool.io/pull/36",
    "diff_url": "https://github.com/bridge-school/bridgeschool.io/pull/36.diff",
    "patch_url": "https://github.com/bridge-school/bridgeschool.io/pull/36.patch",
    "issue_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/36",
    "number": 36,
    "state": "open",
    "locked": false,
    "title": "📣 add open graph meta tags for social",
    "user": {
      "login": "pkanal",
      "id": 8810222,
      "node_id": "MDQ6VXNlcjg4MTAyMjI=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8810222?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pkanal",
      "html_url": "https://github.com/pkanal",
      "followers_url": "https://api.github.com/users/pkanal/followers",
      "following_url": "https://api.github.com/users/pkanal/following{/other_user}",
      "gists_url": "https://api.github.com/users/pkanal/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pkanal/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pkanal/subscriptions",
      "organizations_url": "https://api.github.com/users/pkanal/orgs",
      "repos_url": "https://api.github.com/users/pkanal/repos",
      "events_url": "https://api.github.com/users/pkanal/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pkanal/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "created_at": "2018-07-16T14:35:42Z",
    "updated_at": "2018-07-16T14:35:42Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": "c46cde136736261e20a7e7629b7edcbf40789404",
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "commits_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/36/commits",
    "review_comments_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/36/comments",
    "review_comment_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/36/comments",
    "statuses_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/statuses/0faff5bad6eb49d94e90727791e876e2cd056a4e",
    "head": {
      "label": "bridge-school:chore/add-og-meta-tags",
      "ref": "chore/add-og-meta-tags",
      "sha": "0faff5bad6eb49d94e90727791e876e2cd056a4e",
      "user": {
        "login": "bridge-school",
        "id": 30509997,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNTA5OTk3",
        "avatar_url": "https://avatars0.githubusercontent.com/u/30509997?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bridge-school",
        "html_url": "https://github.com/bridge-school",
        "followers_url": "https://api.github.com/users/bridge-school/followers",
        "following_url": "https://api.github.com/users/bridge-school/following{/other_user}",
        "gists_url": "https://api.github.com/users/bridge-school/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bridge-school/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bridge-school/subscriptions",
        "organizations_url": "https://api.github.com/users/bridge-school/orgs",
        "repos_url": "https://api.github.com/users/bridge-school/repos",
        "events_url": "https://api.github.com/users/bridge-school/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bridge-school/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 98811487,
        "node_id": "MDEwOlJlcG9zaXRvcnk5ODgxMTQ4Nw==",
        "name": "bridgeschool.io",
        "full_name": "bridge-school/bridgeschool.io",
        "private": false,
        "owner": {
          "login": "bridge-school",
          "id": 30509997,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNTA5OTk3",
          "avatar_url": "https://avatars0.githubusercontent.com/u/30509997?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/bridge-school",
          "html_url": "https://github.com/bridge-school",
          "followers_url": "https://api.github.com/users/bridge-school/followers",
          "following_url": "https://api.github.com/users/bridge-school/following{/other_user}",
          "gists_url": "https://api.github.com/users/bridge-school/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/bridge-school/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/bridge-school/subscriptions",
          "organizations_url": "https://api.github.com/users/bridge-school/orgs",
          "repos_url": "https://api.github.com/users/bridge-school/repos",
          "events_url": "https://api.github.com/users/bridge-school/events{/privacy}",
          "received_events_url": "https://api.github.com/users/bridge-school/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/bridge-school/bridgeschool.io",
        "description": "Bridge school's marketing website repo",
        "fork": false,
        "url": "https://api.github.com/repos/bridge-school/bridgeschool.io",
        "forks_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/forks",
        "keys_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/teams",
        "hooks_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/hooks",
        "issue_events_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/events{/number}",
        "events_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/events",
        "assignees_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/assignees{/user}",
        "branches_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/branches{/branch}",
        "tags_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/tags",
        "blobs_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/languages",
        "stargazers_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/stargazers",
        "contributors_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/contributors",
        "subscribers_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/subscribers",
        "subscription_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/subscription",
        "commits_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/contents/{+path}",
        "compare_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/merges",
        "archive_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/downloads",
        "issues_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues{/number}",
        "pulls_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/labels{/name}",
        "releases_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/releases{/id}",
        "deployments_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/deployments",
        "created_at": "2017-07-30T16:49:35Z",
        "updated_at": "2019-01-23T14:47:48Z",
        "pushed_at": "2019-01-23T14:47:46Z",
        "git_url": "git://github.com/bridge-school/bridgeschool.io.git",
        "ssh_url": "git@github.com:bridge-school/bridgeschool.io.git",
        "clone_url": "https://github.com/bridge-school/bridgeschool.io.git",
        "svn_url": "https://github.com/bridge-school/bridgeschool.io",
        "homepage": null,
        "size": 13749,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 2,
        "mirror_url": null,
        "archived": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 2,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "base": {
      "label": "bridge-school:master",
      "ref": "master",
      "sha": "acf081b00f7626b6d0ae658ca0acc14d6fde74bf",
      "user": {
        "login": "bridge-school",
        "id": 30509997,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNTA5OTk3",
        "avatar_url": "https://avatars0.githubusercontent.com/u/30509997?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bridge-school",
        "html_url": "https://github.com/bridge-school",
        "followers_url": "https://api.github.com/users/bridge-school/followers",
        "following_url": "https://api.github.com/users/bridge-school/following{/other_user}",
        "gists_url": "https://api.github.com/users/bridge-school/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bridge-school/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bridge-school/subscriptions",
        "organizations_url": "https://api.github.com/users/bridge-school/orgs",
        "repos_url": "https://api.github.com/users/bridge-school/repos",
        "events_url": "https://api.github.com/users/bridge-school/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bridge-school/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 98811487,
        "node_id": "MDEwOlJlcG9zaXRvcnk5ODgxMTQ4Nw==",
        "name": "bridgeschool.io",
        "full_name": "bridge-school/bridgeschool.io",
        "private": false,
        "owner": {
          "login": "bridge-school",
          "id": 30509997,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjMwNTA5OTk3",
          "avatar_url": "https://avatars0.githubusercontent.com/u/30509997?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/bridge-school",
          "html_url": "https://github.com/bridge-school",
          "followers_url": "https://api.github.com/users/bridge-school/followers",
          "following_url": "https://api.github.com/users/bridge-school/following{/other_user}",
          "gists_url": "https://api.github.com/users/bridge-school/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/bridge-school/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/bridge-school/subscriptions",
          "organizations_url": "https://api.github.com/users/bridge-school/orgs",
          "repos_url": "https://api.github.com/users/bridge-school/repos",
          "events_url": "https://api.github.com/users/bridge-school/events{/privacy}",
          "received_events_url": "https://api.github.com/users/bridge-school/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/bridge-school/bridgeschool.io",
        "description": "Bridge school's marketing website repo",
        "fork": false,
        "url": "https://api.github.com/repos/bridge-school/bridgeschool.io",
        "forks_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/forks",
        "keys_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/teams",
        "hooks_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/hooks",
        "issue_events_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/events{/number}",
        "events_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/events",
        "assignees_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/assignees{/user}",
        "branches_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/branches{/branch}",
        "tags_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/tags",
        "blobs_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/languages",
        "stargazers_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/stargazers",
        "contributors_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/contributors",
        "subscribers_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/subscribers",
        "subscription_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/subscription",
        "commits_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/contents/{+path}",
        "compare_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/merges",
        "archive_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/downloads",
        "issues_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues{/number}",
        "pulls_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/labels{/name}",
        "releases_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/releases{/id}",
        "deployments_url": "https://api.github.com/repos/bridge-school/bridgeschool.io/deployments",
        "created_at": "2017-07-30T16:49:35Z",
        "updated_at": "2019-01-23T14:47:48Z",
        "pushed_at": "2019-01-23T14:47:46Z",
        "git_url": "git://github.com/bridge-school/bridgeschool.io.git",
        "ssh_url": "git@github.com:bridge-school/bridgeschool.io.git",
        "clone_url": "https://github.com/bridge-school/bridgeschool.io.git",
        "svn_url": "https://github.com/bridge-school/bridgeschool.io",
        "homepage": null,
        "size": 13749,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 2,
        "mirror_url": null,
        "archived": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 2,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/36"
      },
      "html": {
        "href": "https://github.com/bridge-school/bridgeschool.io/pull/36"
      },
      "issue": {
        "href": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/36"
      },
      "comments": {
        "href": "https://api.github.com/repos/bridge-school/bridgeschool.io/issues/36/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/36/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/bridge-school/bridgeschool.io/pulls/36/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/bridge-school/bridgeschool.io/statuses/0faff5bad6eb49d94e90727791e876e2cd056a4e"
      }
    },
    "author_association": "MEMBER"
  }
]